#!/usr/bin/env bash
############################################
# Dan Nielsen
# Build and run the app
# Use "run debug" for debug mode
############################################
# Create api/Version.h
# Set APP_DEBUG if "run debug" was called
make version
if [[ "$1" == "debug" ]]; then
  echo \#define APP_DEBUG >> api/Version.h
fi
# Get version string from api/Version.h
ver=$(grep "APP_VERSION" api/Version.h)
tmp=($ver)
ver=${tmp[2]}
echo $ver
# Set version number in web/package.json
node > tmp.json <<EOF
var data = require('./web/package.json');
data.version = $ver;
console.log(JSON.stringify(data,null,2));
EOF
mv tmp.json web/package.json
# Create web/public/version.js
# Set DEBUG if "run debug" was called
echo "const VERSION=$ver;" > web/public/version.js
if [[ "$1" == "debug" ]]; then
  echo "const DEBUG=1;" >> web/public/version.js
fi
# Make
make $1
# Start web server
echo Running $1
npm start
